---
title: 'Class Prep 9: 5.1.1 to 5.3.2'
output:
  word_document: default
  html_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```



# Chapter 5: Differentiation and Integration

## Section 3.1.1: Finite Differences

```{r}
library(cmna)
library(pracma)

finddiff <- function(f, x, h = x*sqrt(.Machine$double.eps)) {
  return((f(x + h) - f(x)) / h)
}

f <- function(x) {3*x - 1}

finddiff(f, 4)
finddiff(f, 4, h=1)
finddiff(f, 4, h=1e-6)


finddiff(sin, pi/4, h=1)
finddiff(sin, pi/4, h=0.5)
finddiff(sin, pi/4, h=0.)

symdiff <- function(f, x, h = x* .Machine$double.eps^(1/3)) {
  return((f(x + h) - f(x - h)) / (2 * h))
}

finddiff(sin, pi/4, h=1e-6)
finddiff(sin, pi/4, h=1e-10)
finddiff(sin, pi/4, h=1e-14)
finddiff(sin, pi/4, h=1e-15)
finddiff(sin, pi/4, h=1e-1)


finddiff(sin, pi/4)

f <- function(x) {x^2 + 3*x - 4}

finddiff(sin, 2)

symdiff(sin, pi/4, h=0.01)
symdiff(sin, pi/4, h=0.001)
symdiff(sin, pi/4, h=0.0001)
symdiff(sin, pi/4)

```


## Section 5.1.2: The Second Derivative

```{r}
finddiff2 <- function(f, x, h) {
  return((f(x + h) - 2*f(x) + f(x - h)) / h^2)
}

finddiff2(sin, pi/4, h = 1e-4); -sin(pi/4)

finddiff2(sin, 3, h = 1e-4); -sin(3)

```

## Section 5.2.1: Multipanel Interpolation Rules

```{r}
midpt <- function(f, a, b, m = 100) {
  nwidth = (b - a) / m
  x = seq(a, b-nwidth, length.out = m) + nwidth / 2
  y = f(x)
  
  area = sum(y) * abs(b - a) / m
  return(area)
}

f <- function(x) { x^2 }

midpt(f, 0, 1, m = 2)
midpt(f, 0, 1, m = 10)
midpt(f, 0, 1, m = 100)
midpt(f, 0, 1, m = 1000)

trap <- function(f, a, b, m = 100) {
  x = seq(a, b, length.out = m+1)
  y = f(x)
  
  p.area = sum((y[2: (m+1)] + y[1:m]))
  p.area = p.area * abs(b - a) / (2 * m)
  return(p.area)
}

simp <- function(f, a, b, m = 100) {
  x.ends = seq(a, b, length.out = m+1)
  y.ends = f(x.ends)
  x.mids = (x.ends[2: (m + 1)] - x.ends[1:m]) / 2 + x.ends[1:m]
  y.mids = f(x.mids)
  
  p.area = sum(y.ends[2: (m+1)] + 4*y.mids[1:m] + y.ends[1:m])
  p.area = p.area * abs(b - a) / (6*m)
  return(p.area)
}

f <- function(x) { x^2 }

trap(f, 0, 1, m = 2)
trap(f, 0, 1, m = 10)
trap(f, 0, 1, m = 100)
trap(f, 0, 1, m = 1000)

simp38 <- function(f, a, b, m = 100) {
  x.ends = seq(a, b, length.out = m + 1)
  y.ends = f(x.ends)
  x.midh = (2 * x.ends[2: (m+1)] + x.ends[1:m]) / 3
  x.midl = (x.ends[2: (m+1)] + 2 * x.ends[1:m]) / 3
  y.midh = f(x.midh)
  y.midl = f(x.midl)
  
  p.area = sum(y.ends[2:(m+1)] + 3 * y.midh[1:m] + 3 * y.midl[1:m] + y.ends[1:m])
  p.area = p.area * abs(b - a) / (8 * m)
  
  return(p.area)
}

midpt(f, 0, 1, m=1)
trap(f, 0, 1, m=1)
simp(f, 0, 1, m=1)
simp38(f, 0, 1, m=1)

f <- function(x) { x^4 - x^2 + 1 }

midpt(f, 0, 1, m=1)
trap(f, 0, 1, m=1)
simp(f, 0, 1, m=1)
simp38(f, 0, 1, m=1)


f <- function(x) { sin(x) + cos(x) }

midpt(f, 0, 1, m=10)
trap(f, 0, 1, m=10)
simp(f, 0, 1, m=10)
simp38(f, 0, 1, m=10)


simp(f, 0, pi, m=2)
simp(f, 0, pi, m=5)
simp(f, 0, pi, m=10)
simp(f, 0, pi, m=100)

simp38(f, 0, pi, m = 2)
simp38(f, 0, pi, m = 5)
simp38(f, 0, pi, m = 10)
simp38(f, 0, pi, m = 100)

```

## Section 5.2.3: Newton-Cotes Forms, Generally

```{r}

trap(log, 0, 1, m=10)
simp(log, 0, 1, m=10)

midpt(f, 0, 1, m=10)
midpt(f, 0, 1, m=100)
midpt(f, 0, 1, m=1000)

f <- function(x) { 1/x }

trap(f, 0, 1, m=100)

midpt(f, 0, 1, m=10)
midpt(f, 0, 1, m=100)
midpt(f, 0, 1, m=1000)

```

## Section 5.3.2: Implementation Details

```{r}
gaussint <- function(f, x, w) {
  y <- f(x)
  
  return(sum(y * w))
}


w = c(1, 1)
x = c(-1 / sqrt(3), 1 / sqrt(3))
f <- function(x) { x^3 + x + 1 }
gaussint(f, x, w)
trap(f, -1, 1, m = 1)
gaussint(cos, x, w)
trap(cos, -1, 1, m = 1)
```