---
title: 'Class Prep 4: 2.3.1 to 2.3.2'
output:
  word_document: default
  html_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```



# Chapter 2: Error Analysis

## Section 2.3.3: Overflow and Underflow

```{r}
library(cmna)
library(pracma)



.Machine$double.xmin
.Machine$double.xmin / 2

.Machine$double.xmax

2147483647L * 2L
2147483647L

.Machine$double.xmax * 2

```


## Section 2.3.4: Error Propogation and Stability

## Section 2.4.1: Simple Division Algorithms


```{r}
naivediv <- function(m, n) {
  quot <- 0
  r <- m
  
  if(n == 0)
    stop("attempted division by 0")
  
  while(r >= n) {
    quot <- quot + 1
    r <- r - n
  }
  
  return(list(quotient = quot, remainder = r))
}

naivediv(314, 7)

floor(314 / 7)
314 %% 7

```



## Section 2.4.2: Binary Long Division

```{r}
longdiv <- function(m, n) {
  quot <- 0
  r <- 0
  
  if(n == 0)
    stop("Attempted division by 0")

  for(i in 31:0) {
    r <- bitwShiftL(r, 1)
    r <- r + bitwAnd(bitwShiftR(m, i), 1)
    if(r >= n) {
      r <- r - n
      quot <- quot + bitwShiftL(1, i)
    }
  }  
  
  return(list(quotient = quot, remainder = r))
}


longdiv(314, 7)


```


# Chapter 3: Linear Algebra

## Section 3.1.1: Vector and Matrix Operations


```{r}
u <- c(1, 2, 3)
v <- c(8, 4, 2)
x <- 7

u + x
u + v

u + c(1, 9)
```

```{r}
A <- Matrix(1:9, 3)
A + 1

A + c(1, 2, 3)

A + 1

A + c(1, 2) - A
A + c(1, 2, 3) - A

B <- Matrix(1:6, 3)
status <- try(A + B)
print(status[1])

A %*% B
u %*% v

diag(A)
diag(B)

diag(u)
diag(1, 4)

nrow(B)
ncol(B)

nrow(u)
ncol(u)

length(u)
length(B)

dim(B)

```








