---
title: 'Class Prep 4: 2.3.1 to 2.3.2'
output:
  word_document: default
  html_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


library(cmna)
library(pracma)

# Chapter 2: Error Analysis

## Section 2.3.1: Round-Off Error and Machine Epsilon

```{r}
.Machine$double.eps

print(1 + .Machine$double.eps, digits = 20)
print(1 + .Machine$double.eps * 2, digits = 20)
print(1 + .Machine$double.eps / 2, digits = 20)

.Machine$double.neg.eps

print(1 - .Machine$double.neg.eps, digits = 20)
print(1 - .Machine$double.neg.eps * 2, digits = 20)
print(1 - .Machine$double.neg.eps / 2, digits = 20)

print(1000 + .Machine$double.eps, digits = 20)

eps(1000)
eps(1000000)
eps(1000000000)
```


## Section 2.3.2: Loss of Significance

```{r}
1 / 3 - 0.333333333333333
1 - 0.999999999999999
(1 - 0.999999999999999) * 1000

20.55 - 19.2 - 1.35
20.55 - 1.35 - 19.2
```

```{r}
quadratic <- function(b2, b1, b0) {
  t1 <- sqrt(b1^2 - 4 * b2 * b0)
  t2 <- 2 * b2
  
  x1 <- - (b1 + t1) / 2
  x2 <- - (b1 - t1) / 2
  
  return(c(x1, x2))
}

quadratic2 <- function(b2, b1, b0) {
  t1 <- sqrt(b1^2 - 4 * b2 * b0)
  t2 <- 2 * b0
  
  x1 <- t2 / (-b1 - t1)
  x2 <- t2 / (-b1 + t1)
  
  ## Reverse the order so they come
  ## back the same as quadratic()
  return(c(x2, x1))
}
```

```{r}
b2 <- 94906265.625
b1 <- 189812534.000
b0 <- 94906268.375

print(quadratic(b2, b1, b0), digits = 20)

print(quadratic2(b2, b1, b0), digits = 20)
```