---
title: 'Class Prep 2: 1.3.2 to 2.1.2'
output:
  word_document: default
  html_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


library(cmna)

# Chapter 1: Introduction to Numerical Analysis

## Section 1.3.2: Evaluating Polynomials

```{r}
  naivepoly <- function(x, coefs) {
    y <- rep(0, length(x))
    
    for(i in 1:length(coefs)) {
      y <- y + coefs[i]*(x^(i-1))
    }
    
    return(y)
  }


  betterpoly <- function(x, coefs) {
    y <- rep(0, length(x))
    cached.x <- 1
    
    for(i in 1:length(coefs)) {
      y <- y + coefs[i] * cached.x
      cached.x <- cached.x * x
    }
    
    
    return(y)
  }
  
  
  horner <- function(x, coefs) {
    y <- rep(0, length(x))
    
    for(i in length(coefs):1) {
      y <- coefs[i] + x * y
    }
    
    return(y)
  }
```

```{r}
  f <- c(30, -19, -15, 3, 1)
  x <- c(-1, 0, 1)
  
  naivepoly(x, f)
  betterpoly(x, f)
  horner(x, f)
```

## Section 1.3.3: The nth Root Algorithm

```{r}
nthroot <- function(a, n, tol = 1 / 1000 ) {
  x <- 1
  deltax <- tol * 10

  while(abs(deltax) > tol) {
    deltax <- (1/n) * (a / (x ^ (n - 1)) - x)
    x <- x + deltax
  }  
  
  return(x)
}

nthroot(100, 2)
nthroot(65536, 4)
nthroot(1000, 3)
nthroot(pi, 2)
```

```{r}
100^.5
65536^(1/4)
1000^(1/3)
pi^.5

```

# Chapter 2: Error Analysis

## Section 2.2.1: Binary Numbers

```{r}
as.integer(2^31 - 2)
as.integer(2^31 - 1)
as.integer(2^31)

-2147483646L
-2147483646L - 1L
-2147483646L - 2L

-2147483646L

as.integer(0.5)
as.integer(1.9)

0xFACE

2^32
class(2^32)
```
